name: Deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: Build and deploy lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}
      # - name: NPM Stuff
      #   run: |
      #     npm ci
      #     npm run build --if-present
      #   env:
      #     CI: true
      - name: Create ZIP Folder
        uses: montudor/action-zip@v0.1.0
        with:
          args: cd src && zip -qq -r ./bundle.zip ./
      - name: Deploy to AWS
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1
          function_name: pushFromGithub
          zip_file: ./src/bundle.zip
